import { useEffect, useRef, useState } from "react";

export default function Mapa() {
    const mapRef = useRef<HTMLDivElement>(null);
    const [shouldLoadMap, setShouldLoadMap] = useState(false);

    useEffect(() => {
      if (!mapRef.current || globalThis.window === undefined) return;

      const observer = new IntersectionObserver(
        (entries) => {
          if (entries[0]?.isIntersecting) {
            setShouldLoadMap(true);
            observer.disconnect();
          }
        },
        { rootMargin: "120px" }
      );

      observer.observe(mapRef.current);

      return () => observer.disconnect();
    }, []);

    useEffect(() => {
      let mapInstance: { remove: () => void } | null = null;
      if (!shouldLoadMap || !mapRef.current || globalThis.window === undefined) return;

      const initMap = async () => {
        const [
          _css,
          leafletModule,
          markerIcon2xMod,
          markerIconMod,
          markerShadowMod,
        ] = await Promise.all([
          import("leaflet/dist/leaflet.css"),
          import("leaflet"),
          import("leaflet/dist/images/marker-icon-2x.png"),
          import("leaflet/dist/images/marker-icon.png"),
          import("leaflet/dist/images/marker-shadow.png"),
        ]);
        const L = leafletModule.default;

        // In production builds, Leaflet's default relative marker paths can break.
        // Set explicit asset URLs generated by Vite.
        const defaultIconPrototype = L.Icon.Default.prototype as {
          _getIconUrl?: unknown;
        };
        delete defaultIconPrototype._getIconUrl;
        L.Icon.Default.mergeOptions({
          iconRetinaUrl: markerIcon2xMod.default,
          iconUrl: markerIconMod.default,
          shadowUrl: markerShadowMod.default,
        });

        if (!mapRef.current || mapRef.current.childNodes.length > 0) return;

        const map = L.map(mapRef.current).setView([10.167399, -85.540736], 13);
        L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
          attribution:
            'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors',
        }).addTo(map);
        L.marker([10.167399, -85.540736]).addTo(map).bindPopup("ASADA Juan Díaz");

        mapInstance = map;
      };

      void initMap();

      return () => {
        mapInstance?.remove();
      };
    }, [shouldLoadMap]);

  return (
    <section aria-label="Mapa de ubicación de ASADA Juan Díaz" className="w-full h-[250px]">
      <div
        ref={mapRef}
        id="map"
        className="w-full h-full z-1"
      />
    </section>
  );
}
