/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolicitudesAfiliacionRouteImport } from './routes/(Solicitudes)/Afiliacion'
import { Route as ContactoSugerenciasRouteImport } from './routes/(Contacto)/Sugerencias'
import { Route as ContactoReportesRouteImport } from './routes/(Contacto)/Reportes'
import { Route as ContactoQuejasRouteImport } from './routes/(Contacto)/Quejas'
import { Route as AboutUsHistoriaRouteImport } from './routes/(AboutUs)/Historia'
import { Route as AboutUsDatosGeneralesRouteImport } from './routes/(AboutUs)/DatosGenerales'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesAfiliacionRoute = SolicitudesAfiliacionRouteImport.update({
  id: '/(Solicitudes)/Afiliacion',
  path: '/Afiliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoSugerenciasRoute = ContactoSugerenciasRouteImport.update({
  id: '/(Contacto)/Sugerencias',
  path: '/Sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoReportesRoute = ContactoReportesRouteImport.update({
  id: '/(Contacto)/Reportes',
  path: '/Reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoQuejasRoute = ContactoQuejasRouteImport.update({
  id: '/(Contacto)/Quejas',
  path: '/Quejas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsHistoriaRoute = AboutUsHistoriaRouteImport.update({
  id: '/(AboutUs)/Historia',
  path: '/Historia',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsDatosGeneralesRoute = AboutUsDatosGeneralesRouteImport.update({
  id: '/(AboutUs)/DatosGenerales',
  path: '/DatosGenerales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/DatosGenerales': typeof AboutUsDatosGeneralesRoute
  '/Historia': typeof AboutUsHistoriaRoute
  '/Quejas': typeof ContactoQuejasRoute
  '/Reportes': typeof ContactoReportesRoute
  '/Sugerencias': typeof ContactoSugerenciasRoute
  '/Afiliacion': typeof SolicitudesAfiliacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/DatosGenerales': typeof AboutUsDatosGeneralesRoute
  '/Historia': typeof AboutUsHistoriaRoute
  '/Quejas': typeof ContactoQuejasRoute
  '/Reportes': typeof ContactoReportesRoute
  '/Sugerencias': typeof ContactoSugerenciasRoute
  '/Afiliacion': typeof SolicitudesAfiliacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/(AboutUs)/DatosGenerales': typeof AboutUsDatosGeneralesRoute
  '/(AboutUs)/Historia': typeof AboutUsHistoriaRoute
  '/(Contacto)/Quejas': typeof ContactoQuejasRoute
  '/(Contacto)/Reportes': typeof ContactoReportesRoute
  '/(Contacto)/Sugerencias': typeof ContactoSugerenciasRoute
  '/(Solicitudes)/Afiliacion': typeof SolicitudesAfiliacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/DatosGenerales'
    | '/Historia'
    | '/Quejas'
    | '/Reportes'
    | '/Sugerencias'
    | '/Afiliacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/DatosGenerales'
    | '/Historia'
    | '/Quejas'
    | '/Reportes'
    | '/Sugerencias'
    | '/Afiliacion'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/(AboutUs)/DatosGenerales'
    | '/(AboutUs)/Historia'
    | '/(Contacto)/Quejas'
    | '/(Contacto)/Reportes'
    | '/(Contacto)/Sugerencias'
    | '/(Solicitudes)/Afiliacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AboutUsDatosGeneralesRoute: typeof AboutUsDatosGeneralesRoute
  AboutUsHistoriaRoute: typeof AboutUsHistoriaRoute
  ContactoQuejasRoute: typeof ContactoQuejasRoute
  ContactoReportesRoute: typeof ContactoReportesRoute
  ContactoSugerenciasRoute: typeof ContactoSugerenciasRoute
  SolicitudesAfiliacionRoute: typeof SolicitudesAfiliacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Solicitudes)/Afiliacion': {
      id: '/(Solicitudes)/Afiliacion'
      path: '/Afiliacion'
      fullPath: '/Afiliacion'
      preLoaderRoute: typeof SolicitudesAfiliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Contacto)/Sugerencias': {
      id: '/(Contacto)/Sugerencias'
      path: '/Sugerencias'
      fullPath: '/Sugerencias'
      preLoaderRoute: typeof ContactoSugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Contacto)/Reportes': {
      id: '/(Contacto)/Reportes'
      path: '/Reportes'
      fullPath: '/Reportes'
      preLoaderRoute: typeof ContactoReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Contacto)/Quejas': {
      id: '/(Contacto)/Quejas'
      path: '/Quejas'
      fullPath: '/Quejas'
      preLoaderRoute: typeof ContactoQuejasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AboutUs)/Historia': {
      id: '/(AboutUs)/Historia'
      path: '/Historia'
      fullPath: '/Historia'
      preLoaderRoute: typeof AboutUsHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AboutUs)/DatosGenerales': {
      id: '/(AboutUs)/DatosGenerales'
      path: '/DatosGenerales'
      fullPath: '/DatosGenerales'
      preLoaderRoute: typeof AboutUsDatosGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AboutUsDatosGeneralesRoute: AboutUsDatosGeneralesRoute,
  AboutUsHistoriaRoute: AboutUsHistoriaRoute,
  ContactoQuejasRoute: ContactoQuejasRoute,
  ContactoReportesRoute: ContactoReportesRoute,
  ContactoSugerenciasRoute: ContactoSugerenciasRoute,
  SolicitudesAfiliacionRoute: SolicitudesAfiliacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
