/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/(Auth)/Login'
import { Route as AuthForgotPasswordRouteImport } from './routes/(Auth)/ForgotPassword'
import { Route as AboutUsMisionVisionRouteImport } from './routes/(AboutUs)/MisionVision'
import { Route as AboutUsHistoriaRouteImport } from './routes/(AboutUs)/Historia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/(Auth)/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/(Auth)/ForgotPassword',
  path: '/ForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsMisionVisionRoute = AboutUsMisionVisionRouteImport.update({
  id: '/(AboutUs)/MisionVision',
  path: '/MisionVision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsHistoriaRoute = AboutUsHistoriaRouteImport.update({
  id: '/(AboutUs)/Historia',
  path: '/Historia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Historia': typeof AboutUsHistoriaRoute
  '/MisionVision': typeof AboutUsMisionVisionRoute
  '/ForgotPassword': typeof AuthForgotPasswordRoute
  '/Login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Historia': typeof AboutUsHistoriaRoute
  '/MisionVision': typeof AboutUsMisionVisionRoute
  '/ForgotPassword': typeof AuthForgotPasswordRoute
  '/Login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(AboutUs)/Historia': typeof AboutUsHistoriaRoute
  '/(AboutUs)/MisionVision': typeof AboutUsMisionVisionRoute
  '/(Auth)/ForgotPassword': typeof AuthForgotPasswordRoute
  '/(Auth)/Login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Historia' | '/MisionVision' | '/ForgotPassword' | '/Login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Historia' | '/MisionVision' | '/ForgotPassword' | '/Login'
  id:
    | '__root__'
    | '/'
    | '/(AboutUs)/Historia'
    | '/(AboutUs)/MisionVision'
    | '/(Auth)/ForgotPassword'
    | '/(Auth)/Login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsHistoriaRoute: typeof AboutUsHistoriaRoute
  AboutUsMisionVisionRoute: typeof AboutUsMisionVisionRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/Login': {
      id: '/(Auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/ForgotPassword': {
      id: '/(Auth)/ForgotPassword'
      path: '/ForgotPassword'
      fullPath: '/ForgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AboutUs)/MisionVision': {
      id: '/(AboutUs)/MisionVision'
      path: '/MisionVision'
      fullPath: '/MisionVision'
      preLoaderRoute: typeof AboutUsMisionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(AboutUs)/Historia': {
      id: '/(AboutUs)/Historia'
      path: '/Historia'
      fullPath: '/Historia'
      preLoaderRoute: typeof AboutUsHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsHistoriaRoute: AboutUsHistoriaRoute,
  AboutUsMisionVisionRoute: AboutUsMisionVisionRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
